export const EventType = {
  EDITOR_DID_MOUNT: Symbol('DID_MOUNT'),
  EDITOR_DID_CHANGE_ACTIVE_CELL: Symbol('DID_CHANGE_ACTIVE_CELL'),
  EDITOR_DID_CHANGE_MOUSE_CELL: Symbol('DID_CHANGE_MOUSE_CELL'),
  EDITOR_DID_CHANGE_OPTIONS: Symbol('DID_CHANGE_OPTIONS'),

  CONTROLLER_WILL_MOUNT: Symbol('WILL_MOUNT'),
  CONTROLLER_DID_MOUNT: Symbol('DID_MOUNT'),
  CONTROLLER_WILL_UNMOUNT: Symbol('WILL_UNMOUNT'),
  CONTROLLER_DID_UNMOUNT: Symbol('DID_UNMOUNT'),

  EXPLORER_WILL_MOUNT: Symbol('WILL_MOUNT'),
  EXPLORER_DID_MOUNT: Symbol('DID_MOUNT'),
  EXPLORER_WILL_UNMOUNT: Symbol('WILL_UNMOUNT'),
  EXPLORER_DID_UNMOUNT: Symbol('DID_UNMOUNT'),
};
