// 内部事件，不向外提供
export const EventType = {
  CONTROLLER_WILL_MOUNT: Symbol('WILL_MOUNT'),
  CONTROLLER_DID_MOUNT: Symbol('DID_MOUNT'),
  CONTROLLER_WILL_UNMOUNT: Symbol('WILL_UNMOUNT'),
  CONTROLLER_DID_UNMOUNT: Symbol('DID_UNMOUNT'),

  EXPLORER_WILL_MOUNT: Symbol('WILL_MOUNT'),
  EXPLORER_DID_MOUNT: Symbol('DID_MOUNT'),
  EXPLORER_WILL_UNMOUNT: Symbol('WILL_UNMOUNT'),
  EXPLORER_DID_UNMOUNT: Symbol('DID_UNMOUNT'),
};

// 分组标识
export const GROUP_TAG = '|';
